name: Build Worker

on:
  pull_request:
    branches:
      - main
    paths:
      - "worker/**"
      - ".github/workflows/call-docker-build-worker.yaml"

  push:
    branches:
      - main
    paths:
      - "worker/**"
      - ".github/workflows/call-docker-build-worker.yaml"

  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build worker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Build worker Docker image
        run: |
          docker build \
            --pull \
            --tag aws-voting-platform-worker:${{ github.sha }} \
            ./worker
