name: Build Vote

on:
  pull_request:
    branches:
      - main
    paths:
      - "vote/**"
      - ".github/workflows/call-docker-build-vote.yaml"

  push:
    branches:
      - main
    paths:
      - "vote/**"
      - ".github/workflows/call-docker-build-vote.yaml"

  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build vote image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Build vote Docker image
        run: |
          docker build \
            --pull \
            --tag aws-voting-platform-vote:${{ github.sha }} \
            ./vote
