name: Build Result

on:
  pull_request:
    branches:
      - main
    paths:
      - "result/**"
      - ".github/workflows/call-docker-build-result.yaml"

  push:
    branches:
      - main
    paths:
      - "result/**"
      - ".github/workflows/call-docker-build-result.yaml"

  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build result image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Build result Docker image
        run: |
          docker build \
            --pull \
            --tag aws-voting-platform-result:${{ github.sha }} \
            ./result
